version: "3.9"

services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"  # Internal PLAINTEXT
      - "9094:9094"  # External access
    volumes:
      - kafka_data:/bitnami
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT


      # Create Topic: job-stream
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    command: >
      bash -c "
        /opt/bitnami/scripts/kafka/run.sh & 
        sleep 15 && 
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic job-stream --partitions 6 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092 &&
        wait
      "
volumes:
  kafka_data:
    driver: local